# this is mysql config
[list]
    [list.default]
        driver_name = "mysql"
        data_source_name = "root:nieaowei520@tcp(rm-wz9229f8eht9g9ih63o.mysql.rds.aliyuncs.com:3306)/go_gateway?charset=utf8&parseTime=true&loc=Asia%2FChongqing"
        max_open_conn = 20
        max_idle_conn = 10
        max_conn_life_time = 100
        
        
