// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/login": {
            "post": {
                "description": "管理员登陆",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员接口"
                ],
                "summary": "管理员登陆",
                "operationId": "/admin/login",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminLoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.AdminLoginOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/logout": {
            "get": {
                "description": "管理员登出",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员接口"
                ],
                "summary": "管理员登出",
                "operationId": "/admin/login",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    }
                }
            }
        },
        "/app/add": {
            "post": {
                "description": "增加租户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "租户接口"
                ],
                "summary": "增加租户",
                "operationId": "/app/add",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddAppInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.AddAppOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/del": {
            "get": {
                "description": "删除租户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "租户接口"
                ],
                "summary": "删除租户",
                "operationId": "/app/del",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteAppInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.DeleteAppOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/detail": {
            "get": {
                "description": "获取租户详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "租户接口"
                ],
                "summary": "获取租户详细信息",
                "operationId": "/app/detail",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 4,
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.GetAppDetailOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/list": {
            "get": {
                "description": "获取租户列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "租户接口"
                ],
                "summary": "获取租户列表",
                "operationId": "/app/list",
                "parameters": [
                    {
                        "type": "string",
                        "name": "info",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 2,
                        "name": "page_no",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "example": 10,
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.GetAppListOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/stat": {
            "get": {
                "description": "获取租户流量统计",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "租户接口"
                ],
                "summary": "获取租户流量统计",
                "operationId": "/app/stat",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 3,
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.GetAppStatOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/update": {
            "post": {
                "description": "更新租户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "租户接口"
                ],
                "summary": "更新租户",
                "operationId": "/app/update",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateAppInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.UpdateAppOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/public/get/avatar": {
            "get": {
                "description": "获取头像",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "公共接口"
                ],
                "summary": "获取头像",
                "operationId": "/public/get/avatar",
                "parameters": [
                    {
                        "type": "string",
                        "name": "username",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.GetAvatarOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/service/del": {
            "get": {
                "description": "删除服务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务接口"
                ],
                "summary": "删除服务",
                "operationId": "/service/del",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 96,
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    }
                }
            }
        },
        "/service/detail": {
            "get": {
                "description": "获取单个服务详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务接口"
                ],
                "summary": "获服务详情",
                "operationId": "/service/detail",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 133,
                        "name": "service_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.GetServiceDetailForHttpOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/service/grpc/add": {
            "post": {
                "description": "增加grpc服务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务接口"
                ],
                "summary": "增加grpc服务",
                "operationId": "/service/grpc/add",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddGrpcServiceInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    }
                }
            }
        },
        "/service/grpc/update": {
            "post": {
                "description": "更新grpc服务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务接口"
                ],
                "summary": "更新grpc服务",
                "operationId": "/service/grpc/update",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateGrpcServiceInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    }
                }
            }
        },
        "/service/http/add": {
            "post": {
                "description": "增加http服务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务接口"
                ],
                "summary": "增加http服务",
                "operationId": "/service/http/add",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddHttpServiceInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    }
                }
            }
        },
        "/service/http/update": {
            "post": {
                "description": "更新http服务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务接口"
                ],
                "summary": "更新http服务",
                "operationId": "/service/http/update",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateHttpServiceInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    }
                }
            }
        },
        "/service/list": {
            "get": {
                "description": "获取服务列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务接口"
                ],
                "summary": "获取服务列表",
                "operationId": "/service/list",
                "parameters": [
                    {
                        "type": "string",
                        "name": "info",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 2,
                        "name": "page_no",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "example": 10,
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.GetServiceListOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/service/stat": {
            "get": {
                "description": "获服务状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务接口"
                ],
                "summary": "获服务状态",
                "operationId": "/service/stat",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 156,
                        "name": "service_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.GetServiceStatOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/service/tcp/add": {
            "post": {
                "description": "增加tcp服务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务接口"
                ],
                "summary": "增加tcp服务",
                "operationId": "/service/tcp/add",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddTcpServiceInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    }
                }
            }
        },
        "/service/tcp/update": {
            "post": {
                "description": "更新tcp服务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务接口"
                ],
                "summary": "更新tcp服务",
                "operationId": "/service/tcp/update",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateTcpServiceInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    }
                }
            }
        },
        "/statistics/service/amount": {
            "get": {
                "description": "获服务统计",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "统计接口"
                ],
                "summary": "获服务统计",
                "operationId": "/statistics/service/amount",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.GetServiceAmountOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/statistics/total": {
            "get": {
                "description": "获取仪表盘统计数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "统计接口"
                ],
                "summary": "获取仪表盘统计数据",
                "operationId": "/statistics/total",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.GetTotalOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AddAppInput": {
            "type": "object",
            "required": [
                "app_id",
                "name"
            ],
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "qpd": {
                    "type": "integer"
                },
                "qps": {
                    "type": "integer"
                }
            }
        },
        "dto.AddAppOutput": {
            "type": "object"
        },
        "dto.AddGrpcServiceInput": {
            "type": "object",
            "required": [
                "ip_list",
                "service_desc",
                "service_name",
                "weight_list"
            ],
            "properties": {
                "black_list": {
                    "type": "string",
                    "example": "192.168.1.0\n122.12.12.3"
                },
                "clientip_flow_limit": {
                    "type": "integer",
                    "example": 23
                },
                "forbid_list": {
                    "type": "string"
                },
                "ip_list": {
                    "type": "string",
                    "example": "172.1.1.1:80\n172.11.1.2:87"
                },
                "metadata_transform": {
                    "type": "string",
                    "example": "add a 32"
                },
                "open_auth": {
                    "type": "integer"
                },
                "port": {
                    "type": "integer",
                    "example": 7777
                },
                "round_type": {
                    "type": "integer",
                    "example": 1
                },
                "service_desc": {
                    "type": "string",
                    "example": "service_test"
                },
                "service_flow_limit": {
                    "type": "integer",
                    "example": 12
                },
                "service_name": {
                    "type": "string",
                    "example": "service_test"
                },
                "upstream_connect_timeout": {
                    "type": "integer",
                    "example": 122
                },
                "upstream_header_timeout": {
                    "type": "integer",
                    "example": 322
                },
                "upstream_idle_timeout": {
                    "type": "integer",
                    "example": 321
                },
                "upstream_max_idle": {
                    "type": "integer",
                    "example": 12
                },
                "weight_list": {
                    "type": "string",
                    "example": "1\n2"
                },
                "white_host_name": {
                    "type": "string",
                    "example": "nekilc.com"
                },
                "white_list": {
                    "type": "string",
                    "example": "172.17.12.1"
                }
            }
        },
        "dto.AddHttpServiceInput": {
            "type": "object",
            "required": [
                "ip_list",
                "rule",
                "service_desc",
                "service_name",
                "weight_list"
            ],
            "properties": {
                "black_list": {
                    "type": "string",
                    "example": "192.168.1.0\n122.12.12.3"
                },
                "clientip_flow_limit": {
                    "type": "integer",
                    "example": 23
                },
                "forbid_list": {
                    "type": "string"
                },
                "header_transform": {
                    "type": "string",
                    "example": "add a 12\nadd b 13"
                },
                "ip_list": {
                    "type": "string",
                    "example": "172.1.1.1:80\n172.11.1.2:87"
                },
                "need_https": {
                    "type": "integer",
                    "example": 1
                },
                "need_strip_uri": {
                    "type": "integer",
                    "example": 1
                },
                "need_websocket": {
                    "type": "integer",
                    "example": 1
                },
                "open_auth": {
                    "type": "integer"
                },
                "round_type": {
                    "type": "integer",
                    "example": 1
                },
                "rule": {
                    "type": "string",
                    "example": "/dsads"
                },
                "rule_type": {
                    "type": "integer",
                    "example": 1
                },
                "service_desc": {
                    "type": "string",
                    "example": "service_test"
                },
                "service_flow_limit": {
                    "type": "integer",
                    "example": 12
                },
                "service_name": {
                    "type": "string",
                    "example": "service_test"
                },
                "upstream_connect_timeout": {
                    "type": "integer",
                    "example": 122
                },
                "upstream_header_timeout": {
                    "type": "integer",
                    "example": 322
                },
                "upstream_idle_timeout": {
                    "type": "integer",
                    "example": 321
                },
                "upstream_max_idle": {
                    "type": "integer",
                    "example": 12
                },
                "url_rewrite": {
                    "type": "string",
                    "example": "add w\ndel 1"
                },
                "weight_list": {
                    "type": "string",
                    "example": "1\n2"
                },
                "white_host_name": {
                    "type": "string",
                    "example": "nekilc.com"
                },
                "white_list": {
                    "type": "string",
                    "example": "172.17.12.1"
                }
            }
        },
        "dto.AddTcpServiceInput": {
            "type": "object",
            "required": [
                "ip_list",
                "service_desc",
                "service_name",
                "weight_list"
            ],
            "properties": {
                "black_list": {
                    "type": "string",
                    "example": "192.168.1.0\n122.12.12.3"
                },
                "clientip_flow_limit": {
                    "type": "integer",
                    "example": 23
                },
                "forbid_list": {
                    "type": "string"
                },
                "ip_list": {
                    "type": "string",
                    "example": "172.1.1.1:80\n172.11.1.2:87"
                },
                "open_auth": {
                    "type": "integer"
                },
                "port": {
                    "type": "integer",
                    "example": 9999
                },
                "round_type": {
                    "type": "integer",
                    "example": 1
                },
                "service_desc": {
                    "type": "string",
                    "example": "service_test"
                },
                "service_flow_limit": {
                    "type": "integer",
                    "example": 12
                },
                "service_name": {
                    "type": "string",
                    "example": "service_test"
                },
                "upstream_connect_timeout": {
                    "type": "integer",
                    "example": 122
                },
                "upstream_header_timeout": {
                    "type": "integer",
                    "example": 322
                },
                "upstream_idle_timeout": {
                    "type": "integer",
                    "example": 321
                },
                "upstream_max_idle": {
                    "type": "integer",
                    "example": 12
                },
                "weight_list": {
                    "type": "string",
                    "example": "1\n2"
                },
                "white_host_name": {
                    "type": "string",
                    "example": "nekilc.com"
                },
                "white_list": {
                    "type": "string",
                    "example": "172.17.12.1"
                }
            }
        },
        "dto.AdminLoginInput": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string",
                    "example": "nieaowei123"
                },
                "username": {
                    "description": "用户名",
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "dto.AdminLoginOutput": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "token"
                }
            }
        },
        "dto.AppListItem": {
            "type": "object",
            "properties": {
                "app_id": {
                    "description": "\u0008租户id",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "description": "租户名称",
                    "type": "string"
                },
                "qpd": {
                    "description": "WhiteIPs string ` + "`" + `json:\"white_ips\"` + "`" + ` // ip白名单，支持前缀匹配",
                    "type": "integer"
                },
                "qps": {
                    "type": "integer"
                },
                "secret": {
                    "description": "密钥",
                    "type": "string"
                }
            }
        },
        "dto.DeleteAppInput": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "dto.DeleteAppOutput": {
            "type": "object"
        },
        "dto.DeleteServiceInput": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 96
                }
            }
        },
        "dto.GetAppDetailInput": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 4
                }
            }
        },
        "dto.GetAppDetailOutput": {
            "type": "object",
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "qpd": {
                    "type": "integer"
                },
                "qps": {
                    "type": "integer"
                }
            }
        },
        "dto.GetAppListInput": {
            "type": "object",
            "required": [
                "page_no",
                "page_size"
            ],
            "properties": {
                "info": {
                    "type": "string"
                },
                "page_no": {
                    "type": "integer",
                    "example": 2
                },
                "page_size": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "dto.GetAppListOutput": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AppListItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.GetAppStatInput": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "dto.GetAppStatOutput": {
            "type": "object",
            "properties": {
                "today_list": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "yesterday_list": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "dto.GetAvatarInput": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.GetAvatarOutput": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                }
            }
        },
        "dto.GetServiceAmountInput": {
            "type": "object"
        },
        "dto.GetServiceAmountOutput": {
            "type": "object",
            "properties": {
                "GRPC": {
                    "type": "integer"
                },
                "HTTP": {
                    "type": "integer"
                },
                "TCP": {
                    "type": "integer"
                }
            }
        },
        "dto.GetServiceDetailForHttpOutput": {
            "type": "object",
            "required": [
                "ip_list",
                "rule",
                "service_desc",
                "service_name",
                "weight_list"
            ],
            "properties": {
                "black_list": {
                    "type": "string",
                    "example": "192.168.1.0\n122.12.12.3"
                },
                "clientip_flow_limit": {
                    "type": "integer",
                    "example": 23
                },
                "forbid_list": {
                    "type": "string"
                },
                "header_transform": {
                    "type": "string",
                    "example": "add a 12\nadd b 13"
                },
                "ip_list": {
                    "type": "string",
                    "example": "172.1.1.1:80\n172.11.1.2:87"
                },
                "need_https": {
                    "type": "integer",
                    "example": 1
                },
                "need_strip_uri": {
                    "type": "integer",
                    "example": 1
                },
                "need_websocket": {
                    "type": "integer",
                    "example": 1
                },
                "open_auth": {
                    "type": "integer"
                },
                "round_type": {
                    "type": "integer",
                    "example": 1
                },
                "rule": {
                    "type": "string",
                    "example": "/dsads"
                },
                "rule_type": {
                    "type": "integer",
                    "example": 1
                },
                "service_desc": {
                    "type": "string",
                    "example": "service_test"
                },
                "service_flow_limit": {
                    "type": "integer",
                    "example": 12
                },
                "service_id": {
                    "type": "integer"
                },
                "service_name": {
                    "type": "string",
                    "example": "service_test"
                },
                "upstream_connect_timeout": {
                    "type": "integer",
                    "example": 122
                },
                "upstream_header_timeout": {
                    "type": "integer",
                    "example": 322
                },
                "upstream_idle_timeout": {
                    "type": "integer",
                    "example": 321
                },
                "upstream_max_idle": {
                    "type": "integer",
                    "example": 12
                },
                "url_rewrite": {
                    "type": "string",
                    "example": "add w\ndel 1"
                },
                "weight_list": {
                    "type": "string",
                    "example": "1\n2"
                },
                "white_host_name": {
                    "type": "string",
                    "example": "nekilc.com"
                },
                "white_list": {
                    "type": "string",
                    "example": "172.17.12.1"
                }
            }
        },
        "dto.GetServiceDetailInput": {
            "type": "object",
            "required": [
                "service_id"
            ],
            "properties": {
                "service_id": {
                    "type": "integer",
                    "example": 133
                }
            }
        },
        "dto.GetServiceListInput": {
            "type": "object",
            "required": [
                "page_no",
                "page_size"
            ],
            "properties": {
                "info": {
                    "type": "string"
                },
                "page_no": {
                    "type": "integer",
                    "example": 2
                },
                "page_size": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "dto.GetServiceListOutput": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ServiceListItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.GetServiceStatInput": {
            "type": "object",
            "properties": {
                "service_id": {
                    "type": "integer",
                    "example": 156
                }
            }
        },
        "dto.GetServiceStatOutput": {
            "type": "object",
            "properties": {
                "today_list": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "yesterday_list": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "dto.GetTotalInput": {
            "type": "object"
        },
        "dto.GetTotalOutput": {
            "type": "object",
            "properties": {
                "qpd": {
                    "type": "integer"
                },
                "qps": {
                    "type": "integer"
                },
                "service_amount": {
                    "type": "integer"
                },
                "tenant_amount": {
                    "type": "integer"
                }
            }
        },
        "dto.Response": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "errmsg": {
                    "type": "string"
                },
                "errno": {
                    "type": "integer"
                },
                "stack": {
                    "type": "object"
                },
                "trace_id": {
                    "type": "object"
                }
            }
        },
        "dto.ServiceListItem": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "load_type": {
                    "type": "string"
                },
                "qpd": {
                    "type": "integer"
                },
                "qps": {
                    "type": "integer"
                },
                "service_desc": {
                    "type": "string"
                },
                "service_name": {
                    "type": "string"
                },
                "total_node": {
                    "type": "integer"
                }
            }
        },
        "dto.UpdateAppInput": {
            "type": "object",
            "required": [
                "app_id",
                "id",
                "name"
            ],
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "qpd": {
                    "type": "integer"
                },
                "qps": {
                    "type": "integer"
                }
            }
        },
        "dto.UpdateAppOutput": {
            "type": "object"
        },
        "dto.UpdateGrpcServiceInput": {
            "type": "object",
            "required": [
                "ip_list",
                "service_desc",
                "service_name",
                "weight_list"
            ],
            "properties": {
                "black_list": {
                    "type": "string",
                    "example": "192.168.1.0\n122.12.12.3"
                },
                "clientip_flow_limit": {
                    "type": "integer",
                    "example": 23
                },
                "forbid_list": {
                    "type": "string"
                },
                "ip_list": {
                    "type": "string",
                    "example": "172.1.1.1:80\n172.11.1.2:87"
                },
                "metadata_transform": {
                    "type": "string",
                    "example": "add a 32"
                },
                "open_auth": {
                    "type": "integer"
                },
                "port": {
                    "type": "integer",
                    "example": 7777
                },
                "round_type": {
                    "type": "integer",
                    "example": 1
                },
                "service_desc": {
                    "type": "string",
                    "example": "service_test"
                },
                "service_flow_limit": {
                    "type": "integer",
                    "example": 12
                },
                "service_id": {
                    "type": "integer"
                },
                "service_name": {
                    "type": "string",
                    "example": "service_test"
                },
                "upstream_connect_timeout": {
                    "type": "integer",
                    "example": 122
                },
                "upstream_header_timeout": {
                    "type": "integer",
                    "example": 322
                },
                "upstream_idle_timeout": {
                    "type": "integer",
                    "example": 321
                },
                "upstream_max_idle": {
                    "type": "integer",
                    "example": 12
                },
                "weight_list": {
                    "type": "string",
                    "example": "1\n2"
                },
                "white_host_name": {
                    "type": "string",
                    "example": "nekilc.com"
                },
                "white_list": {
                    "type": "string",
                    "example": "172.17.12.1"
                }
            }
        },
        "dto.UpdateHttpServiceInput": {
            "type": "object",
            "required": [
                "ip_list",
                "rule",
                "service_desc",
                "service_name",
                "weight_list"
            ],
            "properties": {
                "black_list": {
                    "type": "string",
                    "example": "192.168.1.0\n122.12.12.3"
                },
                "clientip_flow_limit": {
                    "type": "integer",
                    "example": 23
                },
                "forbid_list": {
                    "type": "string"
                },
                "header_transform": {
                    "type": "string",
                    "example": "add a 12\nadd b 13"
                },
                "ip_list": {
                    "type": "string",
                    "example": "172.1.1.1:80\n172.11.1.2:87"
                },
                "need_https": {
                    "type": "integer",
                    "example": 1
                },
                "need_strip_uri": {
                    "type": "integer",
                    "example": 1
                },
                "need_websocket": {
                    "type": "integer",
                    "example": 1
                },
                "open_auth": {
                    "type": "integer"
                },
                "round_type": {
                    "type": "integer",
                    "example": 1
                },
                "rule": {
                    "type": "string",
                    "example": "/dsads"
                },
                "rule_type": {
                    "type": "integer",
                    "example": 1
                },
                "service_desc": {
                    "type": "string",
                    "example": "service_test"
                },
                "service_flow_limit": {
                    "type": "integer",
                    "example": 12
                },
                "service_id": {
                    "type": "integer"
                },
                "service_name": {
                    "type": "string",
                    "example": "service_test"
                },
                "upstream_connect_timeout": {
                    "type": "integer",
                    "example": 122
                },
                "upstream_header_timeout": {
                    "type": "integer",
                    "example": 322
                },
                "upstream_idle_timeout": {
                    "type": "integer",
                    "example": 321
                },
                "upstream_max_idle": {
                    "type": "integer",
                    "example": 12
                },
                "url_rewrite": {
                    "type": "string",
                    "example": "add w\ndel 1"
                },
                "weight_list": {
                    "type": "string",
                    "example": "1\n2"
                },
                "white_host_name": {
                    "type": "string",
                    "example": "nekilc.com"
                },
                "white_list": {
                    "type": "string",
                    "example": "172.17.12.1"
                }
            }
        },
        "dto.UpdateTcpServiceInput": {
            "type": "object",
            "required": [
                "ip_list",
                "service_desc",
                "service_name",
                "weight_list"
            ],
            "properties": {
                "black_list": {
                    "type": "string",
                    "example": "192.168.1.0\n122.12.12.3"
                },
                "clientip_flow_limit": {
                    "type": "integer",
                    "example": 23
                },
                "forbid_list": {
                    "type": "string"
                },
                "ip_list": {
                    "type": "string",
                    "example": "172.1.1.1:80\n172.11.1.2:87"
                },
                "open_auth": {
                    "type": "integer"
                },
                "port": {
                    "type": "integer",
                    "example": 9999
                },
                "round_type": {
                    "type": "integer",
                    "example": 1
                },
                "service_desc": {
                    "type": "string",
                    "example": "service_test"
                },
                "service_flow_limit": {
                    "type": "integer",
                    "example": 12
                },
                "service_id": {
                    "type": "integer"
                },
                "service_name": {
                    "type": "string",
                    "example": "service_test"
                },
                "upstream_connect_timeout": {
                    "type": "integer",
                    "example": 122
                },
                "upstream_header_timeout": {
                    "type": "integer",
                    "example": 322
                },
                "upstream_idle_timeout": {
                    "type": "integer",
                    "example": 321
                },
                "upstream_max_idle": {
                    "type": "integer",
                    "example": 12
                },
                "weight_list": {
                    "type": "string",
                    "example": "1\n2"
                },
                "white_host_name": {
                    "type": "string",
                    "example": "nekilc.com"
                },
                "white_list": {
                    "type": "string",
                    "example": "172.17.12.1"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "BasicAuth": {
            "type": "basic"
        },
        "OAuth2AccessCode": {
            "type": "oauth2",
            "flow": "accessCode",
            "authorizationUrl": "https://example.com/oauth/authorize",
            "tokenUrl": "https://example.com/oauth/token",
            "scopes": {
                "admin": " Grants read and write access to administrative information"
            }
        },
        "OAuth2Application": {
            "type": "oauth2",
            "flow": "application",
            "tokenUrl": "https://example.com/oauth/token",
            "scopes": {
                "admin": " Grants read and write access to administrative information",
                "write": " Grants write access"
            }
        },
        "OAuth2Implicit": {
            "type": "oauth2",
            "flow": "implicit",
            "authorizationUrl": "https://example.com/oauth/authorize",
            "scopes": {
                "admin": " Grants read and write access to administrative information",
                "write": " Grants write access"
            }
        },
        "OAuth2Password": {
            "type": "oauth2",
            "flow": "password",
            "tokenUrl": "https://example.com/oauth/token",
            "scopes": {
                "admin": " Grants read and write access to administrative information",
                "read": " Grants read access",
                "write": " Grants write access"
            }
        }
    },
    "x-extension-openapi": {
        "example": "value on a json format"
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8880",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Swagger Example API",
	Description: "This is a sample server celler server.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
