# this is redis config file
[list]
    [list.default]
        proxy_list = [
            "172.20.0.1:9000",
            "172.20.0.1:9001",
            "172.20.0.1:9002",
            "172.20.0.1:9003",
            "172.20.0.1:9004",
            "172.20.0.1:9005",
        ]
        max_active = 100
        max_idle = 100
        down_grade = false