create table service_load_balance
(
    id                       bigint auto_increment comment '自增主键'
        primary key,
    service_id               bigint        default 0  not null comment '服务id',
    check_method             tinyint(20)   default 0  not null comment '检查方法 0=tcpchk,检测端口是否握手成功',
    check_timeout            int(10)       default 0  not null comment 'check超时时间,单位s',
    check_interval           int           default 0  not null comment '检查间隔, 单位s',
    round_type               tinyint       default 2  not null comment '轮询方式 0=random 1=round-robin 2=weight_round-robin 3=ip_hash',
    ip_list                  varchar(2000) default '' not null comment 'ip列表',
    weight_list              varchar(2000) default '' not null comment '权重列表',
    forbid_list              varchar(2000) default '' not null comment '禁用ip列表',
    upstream_connect_timeout int           default 0  not null comment '建立连接超时, 单位s',
    upstream_header_timeout  int           default 0  not null comment '获取header超时, 单位s',
    upstream_idle_timeout    int(10)       default 0  not null comment '链接最大空闲时间, 单位s',
    upstream_max_idle        int           default 0  not null comment '最大空闲链接数',
    created_at datetime     default current_timestamp not null comment '新增时间',
    updated_at datetime     default current_timestamp not null comment '更新时间',
    deleted_at datetime                                   null comment '删除时间'
)
    comment '网关负载表';

INSERT INTO go_gateway.service_load_balance (id, service_id, check_method, check_timeout, check_interval, round_type, ip_list, weight_list, forbid_list, upstream_connect_timeout, upstream_header_timeout, upstream_idle_timeout, upstream_max_idle) VALUES (162, 35, 0, 2000, 5000, 2, '127.0.0.1:50051', '100', '', 10000, 0, 0, 0);
INSERT INTO go_gateway.service_load_balance (id, service_id, check_method, check_timeout, check_interval, round_type, ip_list, weight_list, forbid_list, upstream_connect_timeout, upstream_header_timeout, upstream_idle_timeout, upstream_max_idle) VALUES (165, 34, 0, 2000, 5000, 2, '100.90.164.31:8072,100.90.163.51:8072,100.90.163.52:8072,100.90.165.32:8072', '50,50,50,80', '', 20000, 20000, 10000, 100);
INSERT INTO go_gateway.service_load_balance (id, service_id, check_method, check_timeout, check_interval, round_type, ip_list, weight_list, forbid_list, upstream_connect_timeout, upstream_header_timeout, upstream_idle_timeout, upstream_max_idle) VALUES (167, 36, 0, 2000, 5000, 2, '100.90.164.31:8072,100.90.163.51:8072,100.90.163.52:8072,100.90.165.32:8072', '50,50,50,80', '100.90.164.31:8072,100.90.163.51:8072', 10000, 10000, 10000, 100);
INSERT INTO go_gateway.service_load_balance (id, service_id, check_method, check_timeout, check_interval, round_type, ip_list, weight_list, forbid_list, upstream_connect_timeout, upstream_header_timeout, upstream_idle_timeout, upstream_max_idle) VALUES (168, 38, 0, 0, 0, 1, '111:111,22:111', '11,11', '111', 1111, 111, 222, 333);
INSERT INTO go_gateway.service_load_balance (id, service_id, check_method, check_timeout, check_interval, round_type, ip_list, weight_list, forbid_list, upstream_connect_timeout, upstream_header_timeout, upstream_idle_timeout, upstream_max_idle) VALUES (169, 41, 0, 0, 0, 1, '111:111,22:111', '11,11', '111', 0, 0, 0, 0);
INSERT INTO go_gateway.service_load_balance (id, service_id, check_method, check_timeout, check_interval, round_type, ip_list, weight_list, forbid_list, upstream_connect_timeout, upstream_header_timeout, upstream_idle_timeout, upstream_max_idle) VALUES (170, 42, 0, 0, 0, 1, '111:111,22:111', '11,11', '111', 0, 0, 0, 0);
INSERT INTO go_gateway.service_load_balance (id, service_id, check_method, check_timeout, check_interval, round_type, ip_list, weight_list, forbid_list, upstream_connect_timeout, upstream_header_timeout, upstream_idle_timeout, upstream_max_idle) VALUES (171, 43, 0, 2, 5, 1, '111:111,22:111', '11,11', '', 1111, 2222, 333, 444);
INSERT INTO go_gateway.service_load_balance (id, service_id, check_method, check_timeout, check_interval, round_type, ip_list, weight_list, forbid_list, upstream_connect_timeout, upstream_header_timeout, upstream_idle_timeout, upstream_max_idle) VALUES (172, 44, 0, 2, 5, 2, '127.0.0.1:8076', '50', '', 0, 0, 0, 0);
INSERT INTO go_gateway.service_load_balance (id, service_id, check_method, check_timeout, check_interval, round_type, ip_list, weight_list, forbid_list, upstream_connect_timeout, upstream_header_timeout, upstream_idle_timeout, upstream_max_idle) VALUES (173, 45, 0, 2, 5, 2, '127.0.0.1:88', '50', '', 0, 0, 0, 0);
INSERT INTO go_gateway.service_load_balance (id, service_id, check_method, check_timeout, check_interval, round_type, ip_list, weight_list, forbid_list, upstream_connect_timeout, upstream_header_timeout, upstream_idle_timeout, upstream_max_idle) VALUES (174, 46, 0, 2, 5, 2, '127.0.0.1:8002', '50', '', 0, 0, 0, 0);
INSERT INTO go_gateway.service_load_balance (id, service_id, check_method, check_timeout, check_interval, round_type, ip_list, weight_list, forbid_list, upstream_connect_timeout, upstream_header_timeout, upstream_idle_timeout, upstream_max_idle) VALUES (175, 47, 0, 2, 5, 2, '12777:11', '11', '', 0, 0, 0, 0);
INSERT INTO go_gateway.service_load_balance (id, service_id, check_method, check_timeout, check_interval, round_type, ip_list, weight_list, forbid_list, upstream_connect_timeout, upstream_header_timeout, upstream_idle_timeout, upstream_max_idle) VALUES (176, 48, 0, 2, 5, 2, '12777:11', '11', '', 0, 0, 0, 0);
INSERT INTO go_gateway.service_load_balance (id, service_id, check_method, check_timeout, check_interval, round_type, ip_list, weight_list, forbid_list, upstream_connect_timeout, upstream_header_timeout, upstream_idle_timeout, upstream_max_idle) VALUES (177, 49, 0, 2, 5, 2, '12777:11', '11', '', 0, 0, 0, 0);
INSERT INTO go_gateway.service_load_balance (id, service_id, check_method, check_timeout, check_interval, round_type, ip_list, weight_list, forbid_list, upstream_connect_timeout, upstream_header_timeout, upstream_idle_timeout, upstream_max_idle) VALUES (178, 50, 0, 2, 5, 2, '127.0.0.1:8001', '50', '', 0, 0, 0, 0);
INSERT INTO go_gateway.service_load_balance (id, service_id, check_method, check_timeout, check_interval, round_type, ip_list, weight_list, forbid_list, upstream_connect_timeout, upstream_header_timeout, upstream_idle_timeout, upstream_max_idle) VALUES (179, 51, 0, 2, 5, 2, '1212:11', '50', '', 0, 0, 0, 0);
INSERT INTO go_gateway.service_load_balance (id, service_id, check_method, check_timeout, check_interval, round_type, ip_list, weight_list, forbid_list, upstream_connect_timeout, upstream_header_timeout, upstream_idle_timeout, upstream_max_idle) VALUES (180, 52, 0, 2, 5, 2, '1212:11', '50', '', 0, 0, 0, 0);
INSERT INTO go_gateway.service_load_balance (id, service_id, check_method, check_timeout, check_interval, round_type, ip_list, weight_list, forbid_list, upstream_connect_timeout, upstream_header_timeout, upstream_idle_timeout, upstream_max_idle) VALUES (181, 53, 0, 2, 5, 2, '1111:11', '111', '', 0, 0, 0, 0);
INSERT INTO go_gateway.service_load_balance (id, service_id, check_method, check_timeout, check_interval, round_type, ip_list, weight_list, forbid_list, upstream_connect_timeout, upstream_header_timeout, upstream_idle_timeout, upstream_max_idle) VALUES (182, 54, 0, 2, 5, 1, '127.0.0.1:80', '50', '', 0, 0, 0, 0);
INSERT INTO go_gateway.service_load_balance (id, service_id, check_method, check_timeout, check_interval, round_type, ip_list, weight_list, forbid_list, upstream_connect_timeout, upstream_header_timeout, upstream_idle_timeout, upstream_max_idle) VALUES (183, 55, 0, 2, 5, 3, '127.0.0.1:81', '50', '', 0, 0, 0, 0);
INSERT INTO go_gateway.service_load_balance (id, service_id, check_method, check_timeout, check_interval, round_type, ip_list, weight_list, forbid_list, upstream_connect_timeout, upstream_header_timeout, upstream_idle_timeout, upstream_max_idle) VALUES (184, 56, 0, 2, 5, 2, '127.0.0.1:2003,127.0.0.1:2004', '50,50', '', 0, 0, 0, 0);
INSERT INTO go_gateway.service_load_balance (id, service_id, check_method, check_timeout, check_interval, round_type, ip_list, weight_list, forbid_list, upstream_connect_timeout, upstream_header_timeout, upstream_idle_timeout, upstream_max_idle) VALUES (185, 57, 0, 2, 5, 2, '127.0.0.1:6379', '50', '', 0, 0, 0, 0);
INSERT INTO go_gateway.service_load_balance (id, service_id, check_method, check_timeout, check_interval, round_type, ip_list, weight_list, forbid_list, upstream_connect_timeout, upstream_header_timeout, upstream_idle_timeout, upstream_max_idle) VALUES (186, 58, 0, 2, 5, 2, '127.0.0.1:50055', '50', '', 0, 0, 0, 0);
INSERT INTO go_gateway.service_load_balance (id, service_id, check_method, check_timeout, check_interval, round_type, ip_list, weight_list, forbid_list, upstream_connect_timeout, upstream_header_timeout, upstream_idle_timeout, upstream_max_idle) VALUES (187, 59, 0, 2, 5, 2, '127.0.0.1:2003,127.0.0.1:2004', '50,50', '', 0, 0, 0, 0);
INSERT INTO go_gateway.service_load_balance (id, service_id, check_method, check_timeout, check_interval, round_type, ip_list, weight_list, forbid_list, upstream_connect_timeout, upstream_header_timeout, upstream_idle_timeout, upstream_max_idle) VALUES (188, 60, 0, 2, 5, 2, '127.0.0.1:2003,127.0.0.1:2004', '50,50', '', 0, 0, 0, 0);
INSERT INTO go_gateway.service_load_balance (id, service_id, check_method, check_timeout, check_interval, round_type, ip_list, weight_list, forbid_list, upstream_connect_timeout, upstream_header_timeout, upstream_idle_timeout, upstream_max_idle) VALUES (189, 61, 0, 2, 5, 2, '127.0.0.1:3003,127.0.0.1:3004', '50,50', '', 0, 0, 0, 0);